package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Agate = lexy.Style{
	Foreground: "white",
	Background: "#333",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#fcc28c",
		lexy.TokenLiteral:  "#fcc28c",
		lexy.TokenBuiltin:  "#ffa",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#888",
		lexy.TokenString:   "#a2fca2",
		lexy.TokenNumber:   "#d36363",
	},
}
