package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Androidstudio = lexy.Style{
	Foreground: "#a9b7c6",
	Background: "#282b2e",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#cc7832",
		lexy.TokenLiteral:  "#6897BB",
		lexy.TokenBuiltin:  "inherit",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#808080",
		lexy.TokenString:   "#6A8759",
		lexy.TokenNumber:   "#6897BB",
	},
}
