package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AnOldHope = lexy.Style{
	Foreground: "#c0c5ce",
	Background: "#1C1D21",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#B45EA4",
		lexy.TokenLiteral:  "#E7CE56",
		lexy.TokenBuiltin:  "#E7CE56",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#B6B18B",
		lexy.TokenString:   "#4FB4D7",
		lexy.TokenNumber:   "#E7CE56",
	},
}
