package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var ArduinoLight = lexy.Style{
	Foreground: "#434f54",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#00979D",
		lexy.TokenLiteral:  "#D35400",
		lexy.TokenBuiltin:  "#D35400",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "rgba(149,165,166,.8)",
		lexy.TokenString:   "#005C5F",
		lexy.TokenNumber:   "#8A7B52",
	},
}
