package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Arta = lexy.Style{
	Foreground: "#aaa",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#6644aa",
		lexy.TokenLiteral:  "#32aaee",
		lexy.TokenBuiltin:  "#32aaee",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#444",
		lexy.TokenString:   "#ffcc33",
		lexy.TokenNumber:   "#00cc66",
	},
}
