package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Ascetic = lexy.Style{
	Foreground: "black",
	Background: "white",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "inherit",
		lexy.TokenLiteral:  "inherit",
		lexy.TokenBuiltin:  "inherit",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#ccc",
		lexy.TokenString:   "#888",
		lexy.TokenNumber:   "inherit",
	},
}
