package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierHeathDark = lexy.Style{
	Foreground: "#ab9bab",
	Background: "#1b181b",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#7b59c0",
		lexy.TokenLiteral:  "#a65926",
		lexy.TokenBuiltin:  "#a65926",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#9e8f9e",
		lexy.TokenString:   "#918b3b",
		lexy.TokenNumber:   "#a65926",
	},
}
