package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierLakesideDark = lexy.Style{
	Foreground: "#7ea2b4",
	Background: "#161b1d",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#6b6bb8",
		lexy.TokenLiteral:  "#935c25",
		lexy.TokenBuiltin:  "#935c25",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#7195a8",
		lexy.TokenString:   "#568c3b",
		lexy.TokenNumber:   "#935c25",
	},
}
