package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierSulphurpoolLight = lexy.Style{
	Foreground: "#5e6687",
	Background: "#f5f7ff",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#6679cc",
		lexy.TokenLiteral:  "#c76b29",
		lexy.TokenBuiltin:  "#c76b29",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#6b7394",
		lexy.TokenString:   "#ac9739",
		lexy.TokenNumber:   "#c76b29",
	},
}
