package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierForestDark = lexy.Style{
	Foreground: "#a8a19f",
	Background: "#1b1918",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#6666ea",
		lexy.TokenLiteral:  "#df5320",
		lexy.TokenBuiltin:  "#df5320",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#9c9491",
		lexy.TokenString:   "#7b9726",
		lexy.TokenNumber:   "#df5320",
	},
}
