package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierPlateauDark = lexy.Style{
	Foreground: "#8a8585",
	Background: "#1b1818",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#8464c4",
		lexy.TokenLiteral:  "#b45a3c",
		lexy.TokenBuiltin:  "#b45a3c",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#7e7777",
		lexy.TokenString:   "#4b8b8b",
		lexy.TokenNumber:   "#b45a3c",
	},
}
