package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierSavannaLight = lexy.Style{
	Foreground: "#526057",
	Background: "#ecf4ee",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#55859b",
		lexy.TokenLiteral:  "#9f713c",
		lexy.TokenBuiltin:  "#9f713c",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#5f6d64",
		lexy.TokenString:   "#489963",
		lexy.TokenNumber:   "#9f713c",
	},
}
