package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierPlateauLight = lexy.Style{
	Foreground: "#585050",
	Background: "#f4ecec",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#8464c4",
		lexy.TokenLiteral:  "#b45a3c",
		lexy.TokenBuiltin:  "#b45a3c",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#655d5d",
		lexy.TokenString:   "#4b8b8b",
		lexy.TokenNumber:   "#b45a3c",
	},
}
