package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierDuneLight = lexy.Style{
	Foreground: "#6e6b5e",
	Background: "#fefbec",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#b854d4",
		lexy.TokenLiteral:  "#b65611",
		lexy.TokenBuiltin:  "#b65611",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#7d7a68",
		lexy.TokenString:   "#60ac39",
		lexy.TokenNumber:   "#b65611",
	},
}
