package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierLakesideLight = lexy.Style{
	Foreground: "#516d7b",
	Background: "#ebf8ff",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#6b6bb8",
		lexy.TokenLiteral:  "#935c25",
		lexy.TokenBuiltin:  "#935c25",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#5a7b8c",
		lexy.TokenString:   "#568c3b",
		lexy.TokenNumber:   "#935c25",
	},
}
