package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierSulphurpoolDark = lexy.Style{
	Foreground: "#979db4",
	Background: "#202746",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#6679cc",
		lexy.TokenLiteral:  "#c76b29",
		lexy.TokenBuiltin:  "#c76b29",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#898ea4",
		lexy.TokenString:   "#ac9739",
		lexy.TokenNumber:   "#c76b29",
	},
}
