package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierForestLight = lexy.Style{
	Foreground: "#68615e",
	Background: "#f1efee",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#6666ea",
		lexy.TokenLiteral:  "#df5320",
		lexy.TokenBuiltin:  "#df5320",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#766e6b",
		lexy.TokenString:   "#7b9726",
		lexy.TokenNumber:   "#df5320",
	},
}
