package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierDuneDark = lexy.Style{
	Foreground: "#a6a28c",
	Background: "#20201d",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#b854d4",
		lexy.TokenLiteral:  "#b65611",
		lexy.TokenBuiltin:  "#b65611",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#999580",
		lexy.TokenString:   "#60ac39",
		lexy.TokenNumber:   "#b65611",
	},
}
