package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierSeasideLight = lexy.Style{
	Foreground: "#5e6e5e",
	Background: "#f4fbf4",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#ad2bee",
		lexy.TokenLiteral:  "#87711d",
		lexy.TokenBuiltin:  "#87711d",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#687d68",
		lexy.TokenString:   "#29a329",
		lexy.TokenNumber:   "#87711d",
	},
}
