package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierSavannaDark = lexy.Style{
	Foreground: "#87928a",
	Background: "#171c19",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#55859b",
		lexy.TokenLiteral:  "#9f713c",
		lexy.TokenBuiltin:  "#9f713c",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#78877d",
		lexy.TokenString:   "#489963",
		lexy.TokenNumber:   "#9f713c",
	},
}
