package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierSeasideDark = lexy.Style{
	Foreground: "#8ca68c",
	Background: "#131513",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#ad2bee",
		lexy.TokenLiteral:  "#87711d",
		lexy.TokenBuiltin:  "#87711d",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#809980",
		lexy.TokenString:   "#29a329",
		lexy.TokenNumber:   "#87711d",
	},
}
