package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierCaveDark = lexy.Style{
	Foreground: "#8b8792",
	Background: "#19171c",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#955ae7",
		lexy.TokenLiteral:  "#aa573c",
		lexy.TokenBuiltin:  "#aa573c",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#7e7887",
		lexy.TokenString:   "#2a9292",
		lexy.TokenNumber:   "#aa573c",
	},
}
