package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierHeathLight = lexy.Style{
	Foreground: "#695d69",
	Background: "#f7f3f7",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#7b59c0",
		lexy.TokenLiteral:  "#a65926",
		lexy.TokenBuiltin:  "#a65926",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#776977",
		lexy.TokenString:   "#918b3b",
		lexy.TokenNumber:   "#a65926",
	},
}
