package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierCaveLight = lexy.Style{
	Foreground: "#585260",
	Background: "#efecf4",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#955ae7",
		lexy.TokenLiteral:  "#aa573c",
		lexy.TokenBuiltin:  "#aa573c",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#655f6d",
		lexy.TokenString:   "#2a9292",
		lexy.TokenNumber:   "#aa573c",
	},
}
