package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtelierEstuaryDark = lexy.Style{
	Foreground: "#929181",
	Background: "#22221b",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#5f9182",
		lexy.TokenLiteral:  "#ae7313",
		lexy.TokenBuiltin:  "#ae7313",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#878573",
		lexy.TokenString:   "#7d9726",
		lexy.TokenNumber:   "#ae7313",
	},
}
