package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtomOneDark = lexy.Style{
	Foreground: "#abb2bf",
	Background: "#282c34",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#c678dd",
		lexy.TokenLiteral:  "#56b6c2",
		lexy.TokenBuiltin:  "#e6c07b",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#5c6370",
		lexy.TokenString:   "#98c379",
		lexy.TokenNumber:   "#d19a66",
	},
}
