package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var AtomOneLight = lexy.Style{
	Foreground: "#383a42",
	Background: "#fafafa",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#a626a4",
		lexy.TokenLiteral:  "#0184bb",
		lexy.TokenBuiltin:  "#c18401",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#a0a1a7",
		lexy.TokenString:   "#50a14f",
		lexy.TokenNumber:   "#986801",
	},
}
