package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var CodepenEmbed = lexy.Style{
	Foreground: "#fff",
	Background: "#222",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#8f9c6c",
		lexy.TokenLiteral:  "#ab875d",
		lexy.TokenBuiltin:  "#ab875d",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#777",
		lexy.TokenString:   "#8f9c6c",
		lexy.TokenNumber:   "#ab875d",
	},
}
