package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var ColorBrewer = lexy.Style{
	Foreground: "#000",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#3182bd",
		lexy.TokenLiteral:  "#31a354",
		lexy.TokenBuiltin:  "#3182bd",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#636363",
		lexy.TokenString:   "#756bb1",
		lexy.TokenNumber:   "#31a354",
	},
}
