package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Darcula = lexy.Style{
	Foreground: "#bababa",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#cb7832",
		lexy.TokenLiteral:  "#6896ba",
		lexy.TokenBuiltin:  "#e0c46c",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#7f7f7f",
		lexy.TokenString:   "#6a8759",
		lexy.TokenNumber:   "#6896ba",
	},
}
