package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Dark = lexy.Style{
	Foreground: "#ddd",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "inherit",
		lexy.TokenLiteral:  "inherit",
		lexy.TokenBuiltin:  "#d88",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#777",
		lexy.TokenString:   "#d88",
		lexy.TokenNumber:   "inherit",
	},
}
