package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Docco = lexy.Style{
	Foreground: "#000",
	Background: "#f8f8ff",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#954121",
		lexy.TokenLiteral:  "#954121",
		lexy.TokenBuiltin:  "#0086b3",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#408080",
		lexy.TokenString:   "#219161",
		lexy.TokenNumber:   "#40a070",
	},
}
