package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Dracula = lexy.Style{
	Foreground: "#f8f8f2",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "inherit",
		lexy.TokenLiteral:  "inherit",
		lexy.TokenBuiltin:  "inherit",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#6272a4",
		lexy.TokenString:   "#f1fa8c",
		lexy.TokenNumber:   "inherit",
	},
}
