package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Far = lexy.Style{
	Foreground: "#0ff",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "inherit",
		lexy.TokenLiteral:  "#0f0",
		lexy.TokenBuiltin:  "#ff0",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#888",
		lexy.TokenString:   "#ff0",
		lexy.TokenNumber:   "#0f0",
	},
}
