package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Foundation = lexy.Style{
	Foreground: "black",
	Background: "#eee",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#099",
		lexy.TokenLiteral:  "#099",
		lexy.TokenBuiltin:  "inherit",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#998",
		lexy.TokenString:   "#d14",
		lexy.TokenNumber:   "#099",
	},
}
