package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Github = lexy.Style{
	Foreground: "#333",
	Background: "#f8f8f8",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#333",
		lexy.TokenLiteral:  "#008080",
		lexy.TokenBuiltin:  "#0086b3",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#998",
		lexy.TokenString:   "#d14",
		lexy.TokenNumber:   "#008080",
	},
}
