package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var GithubGist = lexy.Style{
	Foreground: "#333333",
	Background: "white",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#a71d5d",
		lexy.TokenLiteral:  "#0086b3",
		lexy.TokenBuiltin:  "inherit",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#969896",
		lexy.TokenString:   "#df5000",
		lexy.TokenNumber:   "inherit",
	},
}
