package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Googlecode = lexy.Style{
	Foreground: "black",
	Background: "white",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#008",
		lexy.TokenLiteral:  "#066",
		lexy.TokenBuiltin:  "#606",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#800",
		lexy.TokenString:   "#080",
		lexy.TokenNumber:   "#066",
	},
}
