package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Grayscale = lexy.Style{
	Foreground: "#333",
	Background: "#fff",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#333",
		lexy.TokenLiteral:  "#777",
		lexy.TokenBuiltin:  "#000",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#777",
		lexy.TokenString:   "#333",
		lexy.TokenNumber:   "#777",
	},
}
