package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var GruvboxLight = lexy.Style{
	Foreground: "#3c3836",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#9d0006",
		lexy.TokenLiteral:  "#8f3f71",
		lexy.TokenBuiltin:  "#076678",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "inherit",
		lexy.TokenString:   "#79740e",
		lexy.TokenNumber:   "#8f3f71",
	},
}
