package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var GruvboxDark = lexy.Style{
	Foreground: "#ebdbb2",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#fb4934",
		lexy.TokenLiteral:  "#d3869b",
		lexy.TokenBuiltin:  "#83a598",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "inherit",
		lexy.TokenString:   "#b8bb26",
		lexy.TokenNumber:   "#d3869b",
	},
}
