package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Hopscotch = lexy.Style{
	Foreground: "#b9b5b8",
	Background: "#322931",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#c85e7c",
		lexy.TokenLiteral:  "#fd8b19",
		lexy.TokenBuiltin:  "#fd8b19",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#989498",
		lexy.TokenString:   "#8fc13e",
		lexy.TokenNumber:   "#fd8b19",
	},
}
