package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Hybrid = lexy.Style{
	Foreground: "#c5c8c6",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#81a2be",
		lexy.TokenLiteral:  "#cc6666",
		lexy.TokenBuiltin:  "#de935f",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#707880",
		lexy.TokenString:   "#b5bd68",
		lexy.TokenNumber:   "#cc6666",
	},
}
