package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Idea = lexy.Style{
	Foreground: "#000",
	Background: "#fff",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#000080",
		lexy.TokenLiteral:  "#000080",
		lexy.TokenBuiltin:  "inherit",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#808080",
		lexy.TokenString:   "#008000",
		lexy.TokenNumber:   "inherit",
	},
}
