package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var IrBlack = lexy.Style{
	Foreground: "#f8f8f8",
	Background: "#000",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#96cbfe",
		lexy.TokenLiteral:  "#c6c5fe",
		lexy.TokenBuiltin:  "inherit",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#7c7c7c",
		lexy.TokenString:   "#a8ff60",
		lexy.TokenNumber:   "#ff73fd",
	},
}
