package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var KimbieDark = lexy.Style{
	Foreground: "#d3af86",
	Background: "#221a0f",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#98676a",
		lexy.TokenLiteral:  "#f79a32",
		lexy.TokenBuiltin:  "#f79a32",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#d6baad",
		lexy.TokenString:   "#889b4a",
		lexy.TokenNumber:   "#f79a32",
	},
}
