package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var KimbieLight = lexy.Style{
	Foreground: "#84613d",
	Background: "#fbebd4",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#98676a",
		lexy.TokenLiteral:  "#f79a32",
		lexy.TokenBuiltin:  "#f79a32",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#a57a4c",
		lexy.TokenString:   "#889b4a",
		lexy.TokenNumber:   "#f79a32",
	},
}
