package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Lightfair = lexy.Style{
	Foreground: "#444",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "inherit",
		lexy.TokenLiteral:  "#62bcbc",
		lexy.TokenBuiltin:  "#25c6c6",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#888888",
		lexy.TokenString:   "#4286f4",
		lexy.TokenNumber:   "#4286f4",
	},
}
