package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Magula = lexy.Style{
	Foreground: "black",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "navy",
		lexy.TokenLiteral:  "#800",
		lexy.TokenBuiltin:  "navy",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#777",
		lexy.TokenString:   "#050",
		lexy.TokenNumber:   "#800",
	},
}
