package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Monokai = lexy.Style{
	Foreground: "#ddd",
	Background: "#272822",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "inherit",
		lexy.TokenLiteral:  "inherit",
		lexy.TokenBuiltin:  "#a6e22e",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#75715e",
		lexy.TokenString:   "#a6e22e",
		lexy.TokenNumber:   "inherit",
	},
}
