package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var MonoBlue = lexy.Style{
	Foreground: "#00193a",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "inherit",
		lexy.TokenLiteral:  "#0048ab",
		lexy.TokenBuiltin:  "#0048ab",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#738191",
		lexy.TokenString:   "#0048ab",
		lexy.TokenNumber:   "inherit",
	},
}
