package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var MonokaiSublime = lexy.Style{
	Foreground: "#f8f8f2",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#f92672",
		lexy.TokenLiteral:  "#ae81ff",
		lexy.TokenBuiltin:  "#e6db74",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#75715e",
		lexy.TokenString:   "#e6db74",
		lexy.TokenNumber:   "#ae81ff",
	},
}
