package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Obsidian = lexy.Style{
	Foreground: "#e0e2e4",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "inherit",
		lexy.TokenLiteral:  "inherit",
		lexy.TokenBuiltin:  "#8cbbad",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#818e96",
		lexy.TokenString:   "#ec7600",
		lexy.TokenNumber:   "#ffcd22",
	},
}
