package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Ocean = lexy.Style{
	Foreground: "#c0c5ce",
	Background: "#2b303b",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#b48ead",
		lexy.TokenLiteral:  "#d08770",
		lexy.TokenBuiltin:  "#d08770",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#65737e",
		lexy.TokenString:   "#a3be8c",
		lexy.TokenNumber:   "#d08770",
	},
}
