package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var ParaisoDark = lexy.Style{
	Foreground: "#a39e9b",
	Background: "#2f1e2e",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#815ba4",
		lexy.TokenLiteral:  "#f99b15",
		lexy.TokenBuiltin:  "#f99b15",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#8d8687",
		lexy.TokenString:   "#48b685",
		lexy.TokenNumber:   "#f99b15",
	},
}
