package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var ParaisoLight = lexy.Style{
	Foreground: "#4f424c",
	Background: "#e7e9db",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#815ba4",
		lexy.TokenLiteral:  "#f99b15",
		lexy.TokenBuiltin:  "#f99b15",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#776e71",
		lexy.TokenString:   "#48b685",
		lexy.TokenNumber:   "#f99b15",
	},
}
