package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Pojoaque = lexy.Style{
	Foreground: "#dccf8f",
	Background: "url(./pojoaque.jpg) repeat scroll left top #181914",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#b64926",
		lexy.TokenLiteral:  "#b64926",
		lexy.TokenBuiltin:  "#ffb03b",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#586e75",
		lexy.TokenString:   "#468966",
		lexy.TokenNumber:   "#468966",
	},
}
