package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Purebasic = lexy.Style{
	Foreground: "#000000",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#006666",
		lexy.TokenLiteral:  "#924B72",
		lexy.TokenBuiltin:  "#006666",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#00AAAA",
		lexy.TokenString:   "#0080FF",
		lexy.TokenNumber:   "#000000",
	},
}
