package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Qtcreatordark = lexy.Style{
	Foreground: "#aaaaaa",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#ffff55",
		lexy.TokenLiteral:  "#ff55ff",
		lexy.TokenBuiltin:  "#ff55ff",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#55ffff",
		lexy.TokenString:   "#ff55ff",
		lexy.TokenNumber:   "#ff55ff",
	},
}
