package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Qtcreatorlight = lexy.Style{
	Foreground: "#000000",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#808000",
		lexy.TokenLiteral:  "#000080",
		lexy.TokenBuiltin:  "#008000",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#008000",
		lexy.TokenString:   "#008000",
		lexy.TokenNumber:   "#000080",
	},
}
