package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Railscasts = lexy.Style{
	Foreground: "#e6e1dc",
	Background: "#232323",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#c26230",
		lexy.TokenLiteral:  "inherit",
		lexy.TokenBuiltin:  "#6d9cbe",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#bc9458",
		lexy.TokenString:   "#a5c261",
		lexy.TokenNumber:   "#a5c261",
	},
}
