package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Routeros = lexy.Style{
	Foreground: "#444",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "inherit",
		lexy.TokenLiteral:  "#78A960",
		lexy.TokenBuiltin:  "#0C9A9A",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#888888",
		lexy.TokenString:   "#880000",
		lexy.TokenNumber:   "#880000",
	},
}
