package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var SchoolBook = lexy.Style{
	Foreground: "#3e5915",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "inherit",
		lexy.TokenLiteral:  "inherit",
		lexy.TokenBuiltin:  "#2c009f",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#e60415",
		lexy.TokenString:   "#2c009f",
		lexy.TokenNumber:   "inherit",
	},
}
