package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var ShadesOfPurple = lexy.Style{
	Foreground: "#e3dfff",
	Background: "inherit",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "inherit",
		lexy.TokenLiteral:  "#fa658d",
		lexy.TokenBuiltin:  "#fb9e00",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#ac65ff",
		lexy.TokenString:   "#4cd213",
		lexy.TokenNumber:   "#fa658d",
	},
}
