package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var SolarizedDark = lexy.Style{
	Foreground: "#839496",
	Background: "#002b36",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#859900",
		lexy.TokenLiteral:  "#2aa198",
		lexy.TokenBuiltin:  "#dc322f",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#586e75",
		lexy.TokenString:   "#2aa198",
		lexy.TokenNumber:   "#2aa198",
	},
}
