package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var SolarizedLight = lexy.Style{
	Foreground: "#657b83",
	Background: "#fdf6e3",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#859900",
		lexy.TokenLiteral:  "#2aa198",
		lexy.TokenBuiltin:  "#dc322f",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#93a1a1",
		lexy.TokenString:   "#2aa198",
		lexy.TokenNumber:   "#2aa198",
	},
}
