package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Sunburst = lexy.Style{
	Foreground: "#f8f8f8",
	Background: "#000",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#e28964",
		lexy.TokenLiteral:  "inherit",
		lexy.TokenBuiltin:  "inherit",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#aeaeae",
		lexy.TokenString:   "#65b042",
		lexy.TokenNumber:   "#3387cc",
	},
}
