package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var TomorrowNightEighties = lexy.Style{
	Foreground: "#cccccc",
	Background: "#2d2d2d",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#cc99cc",
		lexy.TokenLiteral:  "#f99157",
		lexy.TokenBuiltin:  "#f99157",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#999999",
		lexy.TokenString:   "#99cc99",
		lexy.TokenNumber:   "#f99157",
	},
}
