package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var TomorrowNightBright = lexy.Style{
	Foreground: "#eaeaea",
	Background: "black",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#c397d8",
		lexy.TokenLiteral:  "#e78c45",
		lexy.TokenBuiltin:  "#e78c45",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#969896",
		lexy.TokenString:   "#b9ca4a",
		lexy.TokenNumber:   "#e78c45",
	},
}
