package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var TomorrowNightBlue = lexy.Style{
	Foreground: "white",
	Background: "#002451",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#ebbbff",
		lexy.TokenLiteral:  "#ffc58f",
		lexy.TokenBuiltin:  "#ffc58f",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#7285b7",
		lexy.TokenString:   "#d1f1a9",
		lexy.TokenNumber:   "#ffc58f",
	},
}
