package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var TomorrowNight = lexy.Style{
	Foreground: "#c5c8c6",
	Background: "#1d1f21",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#b294bb",
		lexy.TokenLiteral:  "#de935f",
		lexy.TokenBuiltin:  "#de935f",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#969896",
		lexy.TokenString:   "#b5bd68",
		lexy.TokenNumber:   "#de935f",
	},
}
