package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Tomorrow = lexy.Style{
	Foreground: "#4d4d4c",
	Background: "white",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#8959a8",
		lexy.TokenLiteral:  "#f5871f",
		lexy.TokenBuiltin:  "#f5871f",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#8e908c",
		lexy.TokenString:   "#718c00",
		lexy.TokenNumber:   "#f5871f",
	},
}
