package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Vs = lexy.Style{
	Foreground: "black",
	Background: "white",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#00f",
		lexy.TokenLiteral:  "#a31515",
		lexy.TokenBuiltin:  "#00f",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#008000",
		lexy.TokenString:   "#a31515",
		lexy.TokenNumber:   "inherit",
	},
}
