package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Vs2015 = lexy.Style{
	Foreground: "#DCDCDC",
	Background: "#1E1E1E",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#569CD6",
		lexy.TokenLiteral:  "#569CD6",
		lexy.TokenBuiltin:  "#4EC9B0",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#57A64A",
		lexy.TokenString:   "#D69D85",
		lexy.TokenNumber:   "#B8D7A3",
	},
}
