package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Xcode = lexy.Style{
	Foreground: "black",
	Background: "#fff",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#aa0d91",
		lexy.TokenLiteral:  "#aa0d91",
		lexy.TokenBuiltin:  "#5c2699",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#006a00",
		lexy.TokenString:   "#c41a16",
		lexy.TokenNumber:   "#1c00cf",
	},
}
