package style
// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Xt256 = lexy.Style{
	Foreground: "#eaeaea",
	Background: "#000",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#fff000",
		lexy.TokenLiteral:  "#ff0000",
		lexy.TokenBuiltin:  "#ff00ff",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#969896",
		lexy.TokenString:   "#00ff00",
		lexy.TokenNumber:   "#ff0000",
	},
}
