package style

// Code generated by mbndr/lexy
// DO NOT EDIT!
// @generated

import "github.com/mbndr/lexy"

var Zenburn = lexy.Style{
	Foreground: "#dcdcdc",
	Background: "#3f3f3f",

	TokenColors: map[lexy.TokenType]string{
		lexy.TokenKeyword:  "#e3ceab",
		lexy.TokenLiteral:  "#efefaf",
		lexy.TokenBuiltin:  "#cc9393",
		lexy.TokenOperator: "inherit", // TODO
		lexy.TokenComment:  "#7f9f7f",
		lexy.TokenString:   "#cc9393",
		lexy.TokenNumber:   "#8cd0d3",
	},
}
